/run/initialize
/tracking/verbose 1

/random/setSeeds 1321 4456

# Set the distance between the generator and the target
/generator/setDistance 40

/process/list

# Farside detector at (0 deg, 140 cm) by default
/filename/setFilename test1.root

/run/printProgress 10
/placement/setDistance -40
/run/beamOn 500

/filename/setFilename test2.root

/placement/addAngle1 0
/placement/addAngle2 -6
/placement/addAngle3 6
/run/printProgress 10
/run/beamOn 500
