/run/initialize
/tracking/verbose 1

/random/setSeeds 1321 4456

# Set the distance between the generator and the target, or the distance is 60 by default
/generator/setDistance 40

/process/list

# A 3 far-side detector test
/filename/setFilename test0107.root
/placement/addAngle1 0
/placement/setDistance 150
/placement/addAngle2 -30
/placement/setDistance 200
/placement/addAngle3 30
/placement/setDistance 150
/run/printProgress 10
/run/beamOn 500
