/run/initialize

/run/verbose 1
/event/verbose 1
/tracking/verbose 1

/gps/particle neutron
/gps/energy 2.45 MeV

/gps/position -17.5981 17.5981 -9.5322 cm 
/gps/direction 1 -1 0

#/gps/pos/type Plane
#/gps/pos/shape Circle
/gps/pos/centre -17.5981 17.5981 -9.5322 cm 
#/gps/pos/radius .1 mm
#/gps/pos/rot1 1 1 0
#/gps/pos/rot2 0 0 1

#/gps/ang/type iso
#/gps/ang/rot1 1 1 0
#/gps/ang/rot2 0 0 1
#/gps/ang/mintheta 3.1 rad
#/gps/ang/maxtheta 3.14159265 rad


/run/printProgress 1000000
/run/beamOn 20000
